spring.application.name=income_expenses
spring.datasource.url=jdbc:postgresql://localhost:5432/training_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

langchain4j.open-ai.chat-model.api-key=${OPENROUTER_API_KEY}
langchain4j.open-ai.chat-model.base-url=https://openrouter.ai/api/v1
langchain4j.open-ai.chat-model.model-name=qwen/qwen3-vl-235b-a22b-instruct
# langchain4j.open-ai.chat-model.model-name=google/gemma-4-26b-a4b-it
# langchain4j.open-ai.chat-model.model-name=qwen/qwen3.6-35b-a3b
# langchain4j.open-ai.chat-model.model-name=qwen/qwen3.5-9b
# langchain4j.open-ai.chat-model.model-name=openai/gpt-4o-mini
langchain4j.open-ai.chat-model.temperature=0.0
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true
langchain4j.open-ai.chat-model.timeout=120s

#spring.main.allow-circular-references=true